name: Run DBT Project

on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC
    - cron: '0 14 * * *' # 2 PM UTC
    - cron: '0 22 * * *' # 10 PM UTC
  workflow_dispatch: # Allows for manual triggering of the workflow

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DBT
        run: |
          cd petro_dbt
          dbt deps
          dbt run

      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update from DBT run at $(date +'%Y-%m-%d %H:%M:%S')"
          git remote set-url origin https://x-access-token:${{ secrets.pat }}@github.com/${{ github.repository }}
          git commit -am "Automated run"
          git push

